// User
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = 'LOGOUT_USER';
export const ME_FROM_TOKEN = 'ME_FROM_TOKEN';

//ACTION 
export const SWITCH_TRACKER  ="SWITCH_TRACKER "
export const SHOW_ADD_TRACKER ="SHOW_ADD_TRACKER"
export const HIDE_ADD_TRACKER ="HIDE_ADD_TRACKER"
